version: 2.1
orbs:
  aws-cli: circleci/aws-cli
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: s3 sync
          command: aws s3 sync public/ s3://kudomundo/page --delete

      - run:
          name: CloudFront invalidate
          command: aws cloudfront create-invalidation --distribution-id E1P85XYM3ZIMR5 --paths "/*"
